using Discord;
using Discord.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISurvivalBot.Commands
{
    public class ToevalCommand : ModuleBase<SocketCommandContext>
    {
        public static Random random = new Random();
        private List<String> cards = new List<string>()
        {
            "Kun jij ook hinken op twee gedachten?",
            "Kiezen voor liefde is soms loslaten.",
            "MEESTERLIJK",
            "Krap zitten maakt flexibel.",
            "Welke steunpilaar gebruik jij vandaag?",
            "Geef je hersens water tot ze bloeien.",
            "Wat wil je niet voelen?",
            "Selecteren, wat is dat?",
            "Als jij het niet doet, wie doet het dan?",
            "Jezelf straffen is \"moordend\".",
            "Uitdagingen zijn er om problemen op te lossen.",
            "Ga eens langs bij jezelf.",
            "Het negatieve heb je ontdekt, nu nog het positieve.",
            "Pak de kans om jezelf op te \"lichten\".",
            "Licht zit in je ogen.",
            "Ken jij de zon achter jouw wolken?",
            "Morgen is over een jaar.",
            "Kijk eens wat vaker in de spiegel van het niets.",
            "Aan alles zit twee kanten, bekijk de andere kant ook eens.",
            "Met wat vul jij je rukzak?",
            "Mijn leraar wist het ook beter.",
            "Wat heb je nodig om jezelf te ontmoeten?",
            "Vergeten hoeft niet, vergeven wel.",
            "Geloof jij ook dat je meer waard bent?",
            "Goed is tweezijdig.",
            "De bloemen zijn vandaag voor jou.",
            "Tegemoettreden is nog geen ontmoeting.",
            "Wanneer ben je in je eigen valkuil gestapt?",
            "Is deze overtuiging van jezelf?",
            "Je hoeftt niet uniek te worden, je bent het al.",
            "Heb jij ook recht op je eigen ontdekking?",
            "Ja maar, is nee.",
            "Onthaasten, is stilstaan in stromend water.",
            "Zijn is de aanvaardig dat je bent.",
            "Gekleurd zijn geeft een palet aan mogelijkheden.",
            "Dat wat je op je pad tegenkomt, heeft je vast iets te zeggen.",
            "Is de ander verantwoordelijk voor jou leven?",
            "Ga je nu goed met jezelf om?",
            "Klein kan groot zijn.",
            "Wij-Zij of Samen?",
            "Lekkere brompot!",
            "Wie het wil zien hoeft geen bril op te zetten.",
            "Diep van binnen, zit daar ook wat?",
            "Als leven leren is en leren is leven, houd je ogen dan open!",
            "Ben je consument of je eigen criticus?",
            "Je kan ook om de berg heen lopen.",
            "Maak het onmogelijke mogelijk.",
            "Doorzetten of drammen?",
            "Drijf eens op de golven mee.",
            "Vindt het gesprek op dit moment in je hoofd plaats?",
            "Hoezo finish?",
            "In welke \"Veilige\" onveiligheid zit ik?",
            "Met welke overtuiging zet jij jezelf vast?",
            "Stroop je mouwen eens naar beneden.",
            "De gekookte kikker had ook niks in de gaten.",
            "Genieten is ook leven.",
            "Geduld is even noodzakelijk als volharding.",
            "Hoor en wederhoor.",
            "Angst, is de uitnodiging om te durven leren.",
            "Wil je jezelf gelukkig zien?",
            "Het weten van nu is niet het weten van toen.",
            "Trek je jas maar eens uit!",
            "Frustraties koesteren is: zitten in een hogedrukpan.",
            "Wat is er mis aan succes?",
            "Is veranderen alleen voor anderen?",
            "Deden je ouders het ook zo?",
            "Eenzaamheid kan je als zaaigoed gebruiken.",
            "Wat, waarom en hoe is een drie-eenheid.",
            "Deze storm gaat ook weer voorbij.",
            "Driemaal links is ook rechts.",
            "Als het beeld in beeld komt, verdwijnt een ander beeld.",
            "Vandaag even niet.",
            "Geweldadigheid kan je inruilen voor weldadig.",
            "Knip eens een gaatje in je gedachte",
            "Jouw rolmodel, had ook een rolmodel.",
            "Ga maar, maar kom ook weer terug.",
            "Beter dan best, waar haal je dat?",
            "Confronteren is: springen in het diepe.",
            "Zoek en jij zal het vinden.",
            "Als je denkt het te weten, komt het niet-weten te voorschijn.", // Tot hier toevalstreffers
            "Je bent eerlijk tegen mezelf!",
            "Je gaat met mij om zoals je wilt dat jij met mij omgaat!",
            "Je verandert wat ik anders wil!",
            "Je kiest zelf met wie ik om wil gaan!",
            "Je bent precies goed zoals ik ben!",
            "Je doet het met plezier!",
            "Je bent vrij!",
            "Je mag een eigen mening hebben!",
            "Je mag zeggen: ik weet het niet!",
            "Je ben trots op mezelf!",
            "Je zeg wat ik voel!",
            "Je laat mijn problemen los!",
            "Je mag nee zeggen!",
            "Je luister naar mezelf door heel stil te zijn!",
            "Je kan altijd opnieuw beginnen!",
            "Je trekt het geluk naar mij toe!",
            "Je bent goed in alles wat je doet!",
            "Je bent je eigen beste vriend(in)!",
            "Je doet alles met aandacht!",
            "We vergeven je!",
            "Je bent rijk!",
            "Je mag fouten maken!",
            "Je bent veilig!",
            "Je ontmoet allemaal vrolijke mensen!",
            "Je kunt zelf kiezen hoe je reageert in een situatie",
            "Je bent dankbaar!",
            "Je bent sterk!",
            "Je bent mooi van binnen en buiten!",
            "We gunnen je het!",
            "Je ziet het goede in mensen!",
            "Je denkt positief!",
            "Je bent tevreden!",
            "Je hebt respect voor anderen!",
            "Je mag boos zijn!",
            "Je mag anders zijn!",
            "Je houdt van jezelf",
            "Je vertrouwt om ons gevoel!",
            "Je bent wijs",
            "Je mag om hulp vragen!",
            "Je bent een doorzetter!",
            "Je zegt duidelijk wat je bedoeld",
            "Je kunt het!",
            "Je durft het, ook al voel je jezelf verlegen!",
            "Je leert jezelf steeds beter kennen!",
            "Je zorgt goed voor jezelf!",
            "Je twijfelt, dus je kunt beter wachten.",
            "Je leert ook van mogelijke dingen.",
            "Je kiest je eigen weg.",
            "Je mag verdrietig zijn!",
            "Je bent zelf verantwoordelijk voor wat je doet.",
            "Je neemt de tijd die je nodig hebt.",
            "Je komt op voor jezelf."
        };


        [Command("spreuk")]
        [Summary("Random spreuk van de dag")]
        public async Task Jamaar(/*[Remainder] string text*/)
        {
            int answer = random.Next(this.cards.Count);
            await Context.Message.ReplyAsync(this.cards[answer]);
        }
    }
}
